title: Blockchain Technology Initiatives
email: contact@blockchaintechnologyinitiatives.org
description: A nonprofit working towards promoting the application of blockchain technology.
baseurl: ""
url: "http://blockchaintechnologyinitiatives.org"
