

title: Blockchain Technology Initiatives
email: contact@bockchaintechnologyinitiatives.io
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

markdown: kramdown

sass:
  sass_dir: _scss
  style: compressed